spring:
  application:
    name: toyproject
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_toy?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&tinyInt1isBit=false
    username: root
    password: 1q2w3e4r!

    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true

#    properties:
#      hibernate:
#        default_batch_fetch_size: 1000

